### ISSUE TITLE
TWO_CYCLE parameters pessimize picosoc icestorm timing

### ISSUE THREAD

**Issue by cibyr** [cliffordwolf/picorv32#105]
Playing with the picosoc example (adding `-retime -abc2` to the `yosys` commandline in the Makefile), I was surprised to see setting these parameters results in worse, not better, timing:

|                     | icetime clock estimate | LCs   |
|---------------------|------------------------|-------|
| Default             | 15.12 MHz              | 4400  |
| `TWO_CYCLE_COMPARE` | 14.18 MHz              |  4421 |
| `TWO_CYCLE_ALU`     | 13.49 MHz              | 4436  |
| Both                | 13.63 MHz              | 4431  |

I don't know how to interpret the net names in `nextpnr`'s critical path report to begin trying to optimize things.

**Comment by cliffordwolf** [comment]
You really need to run pnr multiple times with different seed values and then calculate mean and standard deviation of the results, otherwise you don't even know if there is any real difference or if you are just staring at the noise.

Also, you need to analyse the critical path reports. I would assume the critical path in your case is not even in the ALU, so breaking the ALU data path into two stages won't change anything for the critical path.
