### ISSUE TITLE
simulation error

### ISSUE THREAD

**Issue by bilkarpooja** [cliffordwolf/picorv32#159]
hello this is pooja since from a couple of weeks i m working on picorv32 code bt i m facing one error after simulating the picosoc folder of the picorv32 ,plz  help me to debud this error. the error snap is below
![image](https://user-images.githubusercontent.com/53936697/80277511-0798cb00-870d-11ea-9c0a-d3f2c568378c.png)

![image](https://user-images.githubusercontent.com/53936697/80277631-f7cdb680-870d-11ea-8c45-7374973f3b48.png)

here i m getting xxxx values for cpu rs1 and rs2 wats the problem in it

**Comment by bilkarpooja** [comment]
![image](https://user-images.githubusercontent.com/53936697/80277583-b0472a80-870d-11ea-9126-7e40255e785e.png)
here i m getting xxxx values for cpu rs1 and rs2 wats the problem in it

**Comment by cliffordwolf** [comment]
In the screenshot you provided it complains about not being able to open the file `firmwari.hex`. That's not a filename ever used in the official version of picosoc, so obviously you are using some local modifications. But since you have not provided those local modifications there is no way for someone else to replicate the issue. Thus there is nothing anyone can do to help you sort out this issue.
