### ISSUE TITLE
Potential power savings

### ISSUE THREAD

**Issue by wallclimber21** [cliffordwolf/picorv32#22]
There are several cases in the code with constructs like this:

    cpu_state_ld_rs1: begin 
        ...        
        reg_op2 <= 'bx;

There are similar constructs for reg_out and div.pcpi_rd.

I assume that this construct exists to avoid the area of the feedback mux? 

I'm wondering if the synthesis tools are smart enough to insert a clock gate for those registers instead of clocking out random data at each clock cycle. 

IMO, instead of hoping that this would be the case, the more conservative way would be to remove the x assignment altogether. Feedback muxes don't really exist anymore and have been replaced by clock gates anyway, so the only extra logic cost would be the one to control the clock gate. 

Also, a clock gate on alu_out_q would be nice as well.

**Comment by cliffordwolf** [comment]
Assigning 'x' is very useful for simulation. It makes it much easier to catch and debug synchronization issues.

The synthesis tool is free to do whatever fits the requirements of the synthesis job. It might just clock-gate the FF, it might eliminate a control signal and make one of the non-x branches the default case for when no other branch is used. It is free to simply ignore the assignment. So removing the assignment would just reduce this degrees of freedom for the synthesis tool.

You care about power, maybe the next person cares more about area. Just pass the right flags to your synthesis tool and it should do the right thing. A synthesis tool is always free to simply ignore an x assignment anyways. So removing it should not make anything better.

Consider this example:

```
module demo(input clk, A, B, C, D, E, output reg X);
   always @(posedge clk) begin
     X <= 'bx;
     case (A)
       B: X <= C;
       D: X <= E;
     endcase
   end
endmodule
```

Yosys for example will transform this into the following circuit (`yosys -p 'synth; show' demo.v`):

![image](https://cloud.githubusercontent.com/assets/619764/18380554/2b7afb96-7678-11e6-8fc8-039a010aab85.png)

Notice that the `D` input is unused in the resulting circuit and all the (potentially power consuming) logic driving it could be removed.

At least as it is now I see no reason to switch away from that code pattern.

PS: In many cases the 'x' assignment is immediately followed by a `full_case` that assigns the register in each branch. See for example `alu_out_0` and `alu_out`. In this cases the assignment is for simulation only anyways because synthesis sees a full case and therefore does not bother about any assignments made to the same register earlier.

> Also, a clock gate on alu_out_q would be nice as well.

Are you running dynamic power simulation or are you just looking at the code? I really don't like optimizing things without a metric to compare the before and after situation.. Especially if the optimization comes at a cost such as additional logic for control signals (and verification time to verify the architectural change .. I don't have all the time in the world either :).
