### ISSUE TITLE
Will there be a PicoRV64?

### ISSUE THREAD

**Issue by hypoalex** [cliffordwolf/picorv32#31]
I just think it would be cool if an RV64G design (Rocket?) could fit onto one of the ICE40 FPGAs so there was a relatively easy and open source way to hack on these. I think softfp would actually be fine for porting most software.

I just wanted to talk about this, really. It's not an issue per se.

**Comment by cliffordwolf** [comment]
`RocketTile` from Freedom E300 needs 12138 SB_LUT4 and 68 SB_RAM40_4K when mapped to iCE40 (with Yosys). Just the `Rocket` module itself needs 6694 SB_LUT4 and no SB_RAM40_4K (suggesting that the register file is implemented using logic and FFs instead of block RAMs). This is an RV32IMA core.

RV64G is not just twice the register width, it also adds single and double precision floating point support. No way a Rocket core for this ISA would ever fit in iCE40.

There will never be a PicoRV64. Generally speaking, a 64 bit ISA should be used over a 32 bit ISA if the required address space exceeds the 4GB limitation of 32 bit addresses. If you are using a PicoRV32 in an application where 4GB address space is insufficient, then PicoRV32 probably was not the right choice to begin with: This amount of memory would usually be attached to some kind of DDR memory controller. Not only would such a controller on its own already be significantly larger than PicoRV32 itself, you would also need some kind of cache that again would likely be much larger than the processor core. So there really is nothing to gain in such an application by having an ultra-small processor core.
