### ISSUE TITLE
riscv32imac

### ISSUE THREAD

**Issue by fathomtreelimited** [cliffordwolf/picorv32#51]
Hi!

I am targeting Alpine Linux.

It has been decided that the UNIX/Linux platform ABIs will mandate the A extension. The latest Linux port has removed kernel support for atomic emulation (the cmpxchg syscall). So A is now mandatory for the musl-riscv port given the Linux has removed the syscall.

Can you see picorv32 supporting the A extension?

Thanks.

**Comment by cliffordwolf** [comment]
For the most part atomics are not a cpu feature but a feature of the memory subsystem. What memory interface would you suggest that would support atomics and would not require more resources then the entire processor core itself?

Would you be using uC-Linux for this? (PicoRV32 is of course MMU-less. Just an MMU stand-alone would probably be already larger than the whole PicoRV32 core.)

Also: What multi-core application would that be exactly where PicoRV32 would be a good choice? Since PicoRV32 is not a scalar architecture: Wouldn't it make more sense to switch from one PicoRV32 core to one scalar core, instead of using multiple PicoRV32 cores?

**Comment by fathomtreelimited** [comment]
I have considered adding a PCPI for the 11 "A"  instructions in the spec.

LR
SC
AMOADD
AMOXOR
AMOOR
AMOAND
AMOMIN
AMOMAX
AMOMINU
AMOMAXU
AMOSWAP

**Comment by minexew** [comment]
@cliffordwolf Thanks for keeping this small and simple!

**Comment by DmitryZlobec** [comment]
> For the most part atomics are not a cpu feature but a feature of the memory subsystem. What memory interface would you suggest that would support atomics and would not require more resources then the entire processor core itself?
Your right, but "A" subsystem really needed for supporting baremetall Rust. Without LR/SC impossible to make mutex. but mutex is really need for rust memory model. It is a feature of LLVM , and I could not find solution to make mutex software  without LR/SC.
May be it can be made as simple LW without multiprocessing for unithread application?
